google:
  app_id: 142375776388-1umb67dubl4gi3lqpthef6emqn2b3egt.apps.googleusercontent.com
  app_secret: 9fc9Nkv6_BjO-UFMxqM0Hl2l
aws:
  key: AKIAI76BN6MXH4XQ5AOA
  secret: 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
  bucket: liberty-minterns