google:
  app_id: 142375776388-1umb67dubl4gi3lqpthef6emqn2b3egt.apps.googleusercontent.com
  app_secret: 9fc9Nkv6_BjO-UFMxqM0Hl2l
aws:
  key: AKIAIMN5QDIYXYGKZDJQ
  secret: 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
  bucket: liberty-minterns